### ISSUE TITLE
Confirm `expiresAt` type

### ISSUE THREAD

**Issue by justin-calleja** [tzConnectBerlin/kanvas#159]
https://github.com/tzConnectBerlin/kanvas/blob/staging/store-api-server/src/user/entity/user.entity.ts#L19

Is `UserCart`'s `expiresAt` meant to be a `string` or a `number`? It's typed as `number` but I get:

```
    "expiresAt": "2022-06-26T10:06:00.000Z"
```

in response to `GET users/cart/list?currency=GBP`

**Comment by RKlompUU** [comment]
Fixed in this PR: https://github.com/tzConnectBerlin/kanvas/pull/184
